### ISSUE TITLE
T in ChainOutput is unused

### ISSUE THREAD

**Issue by scharf** [rogeriochaves/litechain#1]
https://github.com/rogeriochaves/litechain/blob/e8bf61e295b47d62a751816b631ea8688a7ff431/litechain/core/chain.py#L30

The Generic Parameter `T` is not used. This makes it a bit annoying to define a `ChainOutput` with a value type because to have to specify some value for `T` to specify the value of `V`:

```python
string_output: ChainOutput[Any,str]
```

**Comment by rogeriochaves** [comment]
indeed, I was planning to remove it already, will get to it soon, thanks for reporting!

**Comment by rogeriochaves** [comment]
fixed in ad9624b24c61bf450c073b192998178b84d15dad :)
